In [1]:
import h5py
import numpy as np
import json

In [2]:
file = h5py.File('/Users/lucamasserano/Desktop/uni/cmu/ada/ada_code/1.hdf5', 'r')
file.keys()

<KeysViewHDF5 ['E', 'hl_x', 'meta', 'y']>

## True energy

In [3]:
true_nrg = file['y']
true_nrg

<HDF5 dataset "y": shape (1200,), type "<f4">

In [4]:
true_nrg[0]

655.69965

## High level features (obsolete version, now done in C++)

In [5]:
hl_feats = file['hl_x']
hl_feats

<HDF5 dataset "hl_x": shape (1200, 7), type "<f4">

In [6]:
hl_feats[0]

array([8.8310101e+02, 9.5349579e+02, 5.2524761e+03, 1.6910354e+04,
       3.8697146e+03, 5.7824880e-01, 7.8367944e+00], dtype=float32)

## Muons hits

Dimensions: (muon, calorimeter, z-cell, x-cell, y-cell). <br>
The dimension named 'calorimeter' apparently is just a *box* containing the actual grid 

In [8]:
hits = file['E']
hits

<HDF5 dataset "E": shape (1200, 1, 50, 32, 32), type "<f4">

#### Features V[0] and V[1]

In [14]:
hits[0][0].shape

(50, 32, 32)

In [28]:
np.where(hits[0][0] <= 0.1)

(array([ 0,  0,  0, ..., 49, 49, 49]),
 array([ 0,  0,  0, ..., 31, 31, 31]),
 array([ 0,  1,  2, ..., 29, 30, 31]))

In [76]:
np.sum(hits[0][0][np.where(hits[0][0] > 0.1)])# + np.sum(hits[0][0][np.where(hits[0][0] > 0.1)])

1.6827272

In [91]:
hits[()].squeeze().sum(axis=(1,2,3), where=(hits[()].squeeze() > 0.1)).shape

(1200,)

In [89]:
hits[()].squeeze().squeeze().shape

(1200, 50, 32, 32)

In [72]:
list(range(len(hits.shape)))[-3:]

[2, 3, 4]

In [59]:
hits[0][0].sum(axis=(0,1,2))

7.836794

## Metadata

In [12]:
metadata = json.loads(file['meta'][()])
metadata

{'e_mean': 0.000518606039858202,
 'e_sum': 31863.155088887936,
 'e_square_sum': 188868.6728268921,
 'len': 1200,
 'hl_feats': ['sume2rz_0',
  'sume2rz_1',
  'sume2rz_2',
  'sume2rz_3',
  'sume2rz_4',
  'rmom',
  'esum'],
 'hl_mean': [6001.090446607977,
  7430.592034116686,
  8066.831258693412,
  7832.179394274016,
  7573.081590550582,
  0.7213336141548932,
  26.552629240739922],
 'hl_sum': [7201308.535929573,
  8916710.440940022,
  9680197.510432094,
  9398615.273128819,
  9087697.908660699,
  865.6003369858718,
  31863.155088887906],
 'hl_square_sum': [123383767717.06184,
  163792438507.3064,
  201351317940.6949,
  186933638557.56647,
  186802666204.0862,
  866.4390811842718,
  6586960.255155739]}